### ISSUE TITLE
Update colorama version

### ISSUE THREAD

**Issue by sobolevn** [lensvol/tokelor#1]
I am trying to update `radon` in `wemake-python-styleguide`, but it fails due to:

```
Updating dependencies
Resolving dependencies... (8.0s)

[SolverProblemError]
Because no versions of tokelor match >0.1.3,<0.2.0
 and tokelor (0.1.3) depends on colorama (0.3.9), tokelor (>=0.1.3,<0.2.0) requires colorama (0.3.9).
And because radon (4.0.0) depends on colorama (>=0.4,<0.5)
 and no versions of radon match >4.0,<5.0, tokelor (>=0.1.3,<0.2.0) is incompatible with radon (>=4.0,<5.0).
So, because wemake-python-styleguide depends on both radon (^4.0) and tokelor (^0.1.3), version solving failed.
```

Can you please update the requirement and release a new version?

**Comment by lensvol** [comment]
Thank you for bringing this to my attention, will try to fix it shortly!

**Comment by lensvol** [comment]
Fixed it in https://github.com/lensvol/tokelor/commit/948f8c80e8165fd04d5bccbc0decf37b52b309c6.

**Comment by lensvol** [comment]
New version is on PyPi as well.

**Comment by sobolevn** [comment]
Done! Thanks https://travis-ci.com/wemake-services/wemake-python-styleguide
